- name: Create symlinks
  command: stow shell vim git
  args:
    chdir: ~/dotfiles

- name: Create Mac specific symlinks
  when: ansible_distribution == 'MacOSX'
  command: stow ghostty karabiner
  args:
    chdir: ~/dotfiles
